/**
 * Emits the database snapshot from the domain models, and checks it for drift.
 *
 *   bun run scripts/ts/schema.ts --emit    # write db/schema.sql
 *   bun run scripts/ts/schema.ts           # fail if the file disagrees with the models
 *
 * Why this shape: a model's field NAMES are introspectable at runtime, but its
 * encoded types are only available at the type level — Effect v4 exposes no
 * runtime accessor for the encoded side. So column names and presence are
 * generated, while column types are declared here and reviewed. That is the
 * highest rung reachable today: drift in the set of columns is impossible,
 * drift in their types is caught by review rather than by construction.
 *
 * The check runs in CI. A model that gains a field fails until the snapshot
 * agrees, which is the point — the schema is a contract, and a slot that needs
 * a new column stops and asks rather than editing it mid-flight.
 */
import * as fs from "node:fs"
import * as path from "node:path"
import { Answer } from "../../packages/domain/src/Answer.ts"
import { DeliveryPlatform, Submission } from "../../packages/domain/src/Delivery.ts"
import { Freshness, Judgement } from "../../packages/domain/src/Freshness.ts"
import { Session } from "../../packages/domain/src/Access.ts"
import { Subscription } from "../../packages/domain/src/Subscription.ts"

const ROOT = path.resolve(import.meta.dirname, "../..")
const TARGET = path.join(ROOT, "db/schema.sql")

/** Column types, declared once because they cannot be read from the model. */
const columnTypes: Record<string, string> = {
  // Identifiers and text.
  profileId: "TEXT NOT NULL",
  principalId: "TEXT NOT NULL",
  platformId: "TEXT NOT NULL",
  jobId: "TEXT NOT NULL",
  id: "TEXT PRIMARY KEY",
  question: "TEXT NOT NULL",
  label: "TEXT NOT NULL",
  value: "TEXT NOT NULL",
  origin: "TEXT NOT NULL",
  name: "TEXT NOT NULL",
  hostPattern: "TEXT NOT NULL",
  applicationUrl: "TEXT NOT NULL",
  detail: "TEXT NOT NULL DEFAULT ''",
  outcome: "TEXT NOT NULL",
  verdict: "TEXT NOT NULL",
  reason: "TEXT NOT NULL DEFAULT ''",
  provider: "TEXT NOT NULL DEFAULT 'none'",
  providerRef: "TEXT NOT NULL DEFAULT ''",
  tokenHash: "TEXT NOT NULL",
  // JSON-encoded structures.
  shape: "TEXT NOT NULL",
  tier: "TEXT NOT NULL",
  viaTier: "TEXT NOT NULL",
  mappings: "TEXT NOT NULL DEFAULT '[]'",
  unanswered: "TEXT NOT NULL DEFAULT '[]'",
  // Booleans stored as 0/1, per Model.BooleanSqlite.
  automationProhibited: "INTEGER NOT NULL DEFAULT 0 CHECK (automationProhibited IN (0,1))",
  humanIntervened: "INTEGER NOT NULL DEFAULT 0 CHECK (humanIntervened IN (0,1))",
  // Numbers.
  seenThrough: "INTEGER NOT NULL DEFAULT 0",
  expiresAt: "INTEGER NOT NULL",
  // Timestamps and optionals.
  createdAt: "TEXT NOT NULL",
  updatedAt: "TEXT NOT NULL",
  learnedAt: "TEXT",
  revokedAt: "TEXT",
}

const models = {
  answers: Answer,
  delivery_platforms: DeliveryPlatform,
  submissions: Submission,
  freshness: Freshness,
  judgements: Judgement,
  sessions: Session,
  subscriptions: Subscription,
} as const

const fieldsOf = (model: unknown): ReadonlyArray<string> => {
  const candidate = model as { select?: { fields?: object }; fields?: object }
  const fields = candidate.select?.fields ?? candidate.fields ?? {}
  return Object.keys(fields)
}

const render = (): string => {
  const lines: Array<string> = [
    "-- Generated by scripts/ts/schema.ts from the domain models.",
    "-- Column names are derived; types are declared in that script and reviewed.",
    "-- Re-run with --emit after a model changes. Nothing else may edit this file.",
    "",
  ]
  for (const [table, model] of Object.entries(models)) {
    const columns = fieldsOf(model).map((field) => {
      const type = columnTypes[field]
      if (type === undefined) {
        throw new Error(`no column type declared for ${table}.${field}; add one to scripts/ts/schema.ts`)
      }
      return `  ${field} ${type}`
    })
    lines.push(`CREATE TABLE IF NOT EXISTS ${table} (`, columns.join(",\n"), ");", "")
  }
  return lines.join("\n")
}

const emitted = render()

if (process.argv.includes("--emit")) {
  fs.mkdirSync(path.dirname(TARGET), { recursive: true })
  fs.writeFileSync(TARGET, emitted)
  process.stdout.write(`wrote ${path.relative(ROOT, TARGET)}\n`)
} else {
  const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, "utf8") : ""
  if (current !== emitted) {
    process.stderr.write("db/schema.sql disagrees with the domain models; run with --emit\n")
    process.exit(1)
  }
  process.stdout.write("schema snapshot matches the domain models\n")
}
