-- Generated by scripts/import_source_index.py from
-- research/input/platform-index.csv. Do not edit by hand:
-- re-run the importer so the sheet stays the single source of truth.

INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'arbeidsplassen-nav', 'Arbeidsplassen (NAV)', 'National / general',
  'Primary job board', 'Norway', 'High',
  'Norwegian + some English', 'https://arbeidsplassen.nav.no/stillinger', 'https://arbeidsplassen.nav.no/stillinger',
  '1 Core', 'High', 'Verified active',
  'feed', 'assisted_only', 0,
  'Official national vacancy service. Useful filter: jobs that do not require a driving licence.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'finn-jobb', 'FINN Jobb', 'National / general',
  'Primary job board', 'Norway', 'High',
  'Mostly Norwegian', 'https://www.finn.no/job/', 'https://www.finn.no/job/',
  '1 Core', 'High', 'Verified active',
  'agent', 'prohibited', 1,
  'One of Norway’s largest commercial job boards.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobbnorge', 'Jobbnorge', 'National / general',
  'Primary job board / ATS', 'Norway', 'High',
  'Norwegian + English', 'https://www.jobbnorge.no/search/en', 'https://www.jobbnorge.no/search/en',
  '1 Core', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Strong for public and academic vacancies.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'webcruiter', 'Webcruiter', 'National / general',
  'ATS with public vacancy index', 'Norway', 'High',
  'Norwegian + English', 'https://candidate.webcruiter.com/nb-no/home/alladverts', 'https://candidate.webcruiter.com/nb-no/home/alladverts',
  '1 Core', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Many Norwegian employers publish directly through this ATS.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'linkedin-jobs', 'LinkedIn Jobs', 'National / general',
  'Professional network / job board', 'Norway + global', 'High',
  'Norwegian + English', 'https://www.linkedin.com/jobs/jobs-in-norway/', 'https://www.linkedin.com/jobs/jobs-in-norway/',
  '1 Core', 'High', 'Verified active',
  'agent', 'prohibited', 1,
  'Strong Oslo and international-company coverage; also useful for recruiter discovery.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'indeed-norway', 'Indeed Norway', 'National / general',
  'Aggregator / job board', 'Norway', 'High',
  'Mostly Norwegian', 'https://no.indeed.com/', 'https://no.indeed.com/',
  '1 Core', 'High', 'Verified active',
  'agent', 'prohibited', 1,
  'Check the employer’s original ad before applying.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'glassdoor-norway', 'Glassdoor Norway', 'National / general',
  'Aggregator + employer reviews', 'Norway + global', 'High',
  'Mostly English', 'https://www.glassdoor.com/Job/norway-jobs-SRCH_IL.0,6_IN180.htm', 'https://www.glassdoor.com/Job/norway-jobs-SRCH_IL.0,6_IN180.htm',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'prohibited', 1,
  'Useful for company research as well as listings.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobbsafari', 'Jobbsafari', 'National / general',
  'Aggregator / job board', 'Norway', 'High',
  'Norwegian', 'https://www.jobbsafari.no/', 'https://www.jobbsafari.no/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Often overlaps with primary boards.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'careerjet-norway', 'Careerjet Norway', 'National / general',
  'Aggregator', 'Norway', 'High',
  'Norwegian + English', 'https://www.careerjet.no/', 'https://www.careerjet.no/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Use as a coverage check rather than the only source.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jooble-norway', 'Jooble Norway', 'National / general',
  'Aggregator', 'Norway', 'High',
  'Norwegian + English', 'https://no.jooble.org/', 'https://no.jooble.org/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'May redirect through several layers; find the original ad.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'talent-com-norway', 'Talent.com Norway', 'National / general',
  'Aggregator', 'Norway', 'High',
  'Norwegian + English', 'https://no.talent.com/', 'https://no.talent.com/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Supplementary search engine.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'grabjobs-oslo', 'GrabJobs Oslo', 'Oslo / international',
  'Aggregator / job board', 'Oslo + Norway', 'High',
  'English + Norwegian', 'https://grabjobs.co/norway/jobs-in-oslo', 'https://grabjobs.co/norway/jobs-in-oslo',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Dedicated Oslo search pages.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobs-no', 'Jobs.no', 'National / general',
  'Job board', 'Norway', 'Medium',
  'Norwegian', 'https://www.jobs.no/', 'https://www.jobs.no/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Smaller general board.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'karrierestart', 'KarriereStart', 'National / general',
  'Career portal / job board', 'Norway', 'High',
  'Norwegian', 'https://karrierestart.no/ledig-stilling', 'https://karrierestart.no/ledig-stilling',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Also powers some partner-branded job portals.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'oslopolitan-jobs', 'Oslopolitan Jobs', 'Oslo / international',
  'Partner job portal', 'Oslo region', 'High',
  'English-friendly', 'https://www.oslopolitan.no/jobs', 'https://www.oslopolitan.no/jobs',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Useful for English-speaking and internationally oriented roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobsinoslo', 'JobsinOslo', 'Oslo / international',
  'English-language job board', 'Oslo + Norway', 'High',
  'English', 'https://jobsinoslo.com/', 'https://jobsinoslo.com/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Part of the Jobsin Network.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'englishjobs-no', 'EnglishJobs.no', 'Oslo / international',
  'English-language aggregator', 'Norway', 'High',
  'English', 'https://englishjobs.no/', 'https://englishjobs.no/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Good supplementary filter; verify the original listing.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'eures', 'EURES', 'Oslo / international',
  'Official European job network', 'Norway + EEA', 'High',
  'Multilingual', 'https://eures.europa.eu/jobseekers_en', 'https://eures.europa.eu/jobseekers_en',
  '2 Supplemental', 'High', 'Verified active',
  'feed', 'assisted_only', 0,
  'Official EU/EEA mobility portal.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'europass-find-jobs', 'Europass Find Jobs', 'Oslo / international',
  'Official European search portal', 'Europe incl. Norway', 'Medium',
  'Multilingual', 'https://europa.eu/europass/en/find-jobs', 'https://europa.eu/europass/en/find-jobs',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Overlaps heavily with EURES.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'oslo-kommune-ledige-stillinger', 'Oslo kommune – ledige stillinger', 'Public sector',
  'Employer network / public portal', 'Oslo', 'High',
  'Norwegian', 'https://www.oslo.kommune.no/ledige-stillinger/', 'https://www.oslo.kommune.no/ledige-stillinger/',
  '1 Core', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Major Oslo employer with many role types.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'kommunaljobb', 'Kommunaljobb', 'Public sector',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://www.kommunaljobb.no/', 'https://www.kommunaljobb.no/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Useful alongside Arbeidsplassen and Webcruiter.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'forsvaret-ledige-stillinger', 'Forsvaret – ledige stillinger', 'Public sector',
  'Employer network / public portal', 'Norway', 'Medium',
  'Norwegian', 'https://www.forsvaret.no/jobb/ledige-stillinger', 'https://www.forsvaret.no/jobb/ledige-stillinger',
  '3 Niche', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Some roles have citizenship, clearance, fitness or location constraints.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'politiet-ledige-stillinger', 'Politiet – ledige stillinger', 'Public sector',
  'Employer network / public portal', 'Norway', 'High',
  'Norwegian', 'https://www.politiet.no/om-politiet/jobb-i-politiet/ledige-stillinger/', 'https://www.politiet.no/om-politiet/jobb-i-politiet/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Listings are also commonly mirrored to Arbeidsplassen.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'the-hub', 'The Hub', 'Tech / startup',
  'Startup job board', 'Nordics incl. Norway', 'High',
  'Mostly English', 'https://thehub.io/jobs?countryCode=NO', 'https://thehub.io/jobs?countryCode=NO',
  '1 Core', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Primary Nordic startup board; absorbed Startupmatcher.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'startuplab-jobs', 'StartupLab Jobs', 'Tech / startup',
  'Startup ecosystem job board', 'Norway / Oslo', 'High',
  'English + Norwegian', 'https://jobs.startuplab.no/', 'https://jobs.startuplab.no/',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Strong local startup ecosystem source.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'kodejobb', 'Kodejobb', 'Tech / startup',
  'Developer job board', 'Norway', 'High',
  'Norwegian', 'https://kodejobb.no/', 'https://kodejobb.no/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Developer-focused Norwegian board.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'tekjobb', 'Tekjobb', 'Tech / startup',
  'Engineering / technology job board', 'Norway', 'High',
  'Norwegian', 'https://www.tekjobb.no/', 'https://www.tekjobb.no/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'assisted_only', 1,
  'Operated in the TU Media ecosystem.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'startup-jobs-norway', 'Startup.jobs Norway', 'Tech / startup',
  'Global startup job board', 'Norway filter', 'Medium',
  'English', 'https://startup.jobs/locations/norway', 'https://startup.jobs/locations/norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Supplementary global startup source.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'startupmap-oslo', 'StartupMap Oslo', 'Tech / startup',
  'Ecosystem directory / jobs', 'Oslo', 'High',
  'English', 'https://startupmap.no/', 'https://startupmap.no/',
  '3 Niche', 'Medium', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Useful for company discovery even when jobs are linked externally.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'nordictechjobs-norway', 'NordicTechJobs Norway', 'Tech / startup',
  'Tech job board', 'Norway / Nordics', 'Medium',
  'English', 'https://nordictechjobs.com/jobs/norway', 'https://nordictechjobs.com/jobs/norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Nordic-specific technology listings.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'wellfound', 'Wellfound', 'Tech / startup',
  'Startup talent marketplace', 'Global with Norway filter', 'Medium',
  'English', 'https://wellfound.com/location/norway', 'https://wellfound.com/location/norway',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Formerly AngelList Talent.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'f6s-jobs-norway', 'F6S Jobs Norway', 'Tech / startup',
  'Startup community / job board', 'Norway filter', 'Medium',
  'English', 'https://www.f6s.com/jobs/norway', 'https://www.f6s.com/jobs/norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Coverage varies.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'meetfrank-norway', 'MeetFrank Norway', 'Tech / startup',
  'Job-matching marketplace', 'Norway', 'High',
  'English', 'https://meetfrank.com/jobs/norway', 'https://meetfrank.com/jobs/norway',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'App-first matching and salary-oriented discovery.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'tenth-revolution-group-norway', 'Tenth Revolution Group Norway', 'Tech / startup',
  'Specialist recruiter board', 'Norway', 'High',
  'English + Norwegian', 'https://www.tenthrevolution.com/no/ledige-stillinger', 'https://www.tenthrevolution.com/no/ledige-stillinger',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Specialist technology recruitment brands.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobteaser', 'JobTeaser', 'Student / graduate',
  'Student and graduate platform', 'Norway + Europe', 'High',
  'English + Norwegian', 'https://www.jobteaser.com/en/job-offers', 'https://www.jobteaser.com/en/job-offers',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Graduateland has been folded into JobTeaser.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'academic-work-norway', 'Academic Work Norway', 'Student / graduate',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian + English', 'https://www.academicwork.no/ledige-stillinger', 'https://www.academicwork.no/ledige-stillinger',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Often targets students and recent graduates.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'studentconsulting-norway', 'StudentConsulting Norway', 'Student / graduate',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://www.studentconsulting.com/no/ledige-stillinger/', 'https://www.studentconsulting.com/no/ledige-stillinger/',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Useful for entry-level and flexible work.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'uio-career-opportunities', 'UiO Career Opportunities', 'Student / graduate',
  'University career portal', 'Oslo / Norway', 'High',
  'English + Norwegian', 'https://www.uio.no/english/studies/career/career-opportunities/', 'https://www.uio.no/english/studies/career/career-opportunities/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Especially relevant to UiO students and recent graduates.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'nordjobb', 'Nordjobb', 'Student / graduate',
  'Nordic seasonal-work programme', 'Nordics incl. Norway', 'Medium',
  'Scandinavian + English', 'https://www.nordjobb.org/en/', 'https://www.nordjobb.org/en/',
  '3 Niche', 'Medium', 'Seasonal / active',
  'agent', 'unreviewed', 1,
  'Age and Nordic-language/residency eligibility can apply.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'utdanningsnytt-stillinger', 'Utdanningsnytt Stillinger', 'Education',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://www.utdanningsnytt.no/stillinger', 'https://www.utdanningsnytt.no/stillinger',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Specialist source for education roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'euraxess-jobs', 'EURAXESS Jobs', 'Academic / research',
  'Official research job network', 'Europe incl. Norway', 'High',
  'English', 'https://euraxess.ec.europa.eu/jobs/search', 'https://euraxess.ec.europa.eu/jobs/search',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Official European research careers portal.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'academic-positions-norway', 'Academic Positions Norway', 'Academic / research',
  'Academic job board', 'Norway filter', 'High',
  'English', 'https://academicpositions.com/jobs/country/norway', 'https://academicpositions.com/jobs/country/norway',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Good international-facing academic coverage.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'university-positions-norway', 'University Positions Norway', 'Academic / research',
  'Academic job board', 'Norway', 'High',
  'English + Norwegian', 'https://universitypositions.no/', 'https://universitypositions.no/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Dedicated Norwegian academic portal.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'khrono-stillinger', 'Khrono Stillinger', 'Academic / research',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://stilling.khrono.no/', 'https://stilling.khrono.no/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Covers academic, technical, administrative and communications roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'adecco-norway', 'Adecco Norway', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian + English', 'https://www.adecco.com/nb-no/ledige-stillinger', 'https://www.adecco.com/nb-no',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Large general staffing agency.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'manpower-norway', 'Manpower Norway', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://www.manpower.no/nb/sok', 'https://www.manpower.no/nb/sok',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Large general staffing agency.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'randstad-norway', 'Randstad Norway', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian + English', 'https://www.randstad.no/ledige-stillinger/', 'https://www.randstad.no/ledige-stillinger/',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Large recruiter with Oslo coverage.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobzone', 'Jobzone', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://jobzone.no/ledige-stillinger', 'https://jobzone.no/',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'More than 30 local offices and broad sector coverage.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'personalhuset', 'Personalhuset', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://www.personalhuset.no/ledige-stillinger', 'https://www.personalhuset.no/',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'National staffing and recruitment provider.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'temp-team-norway', 'Temp-Team Norway', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://temp-team.no/ledige-stillinger', 'https://temp-team.no/ledige-stillinger',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'General staffing board.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'eterni', 'Eterni', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian + English', 'https://eterni.no/ledige-stillinger/', 'https://eterni.no/ledige-stillinger/',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Strong in staffing-intensive sectors.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'workshop-bemanning', 'Workshop Bemanning', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://www.workshop.no/ledige-stillinger', 'https://www.workshop.no/ledige-stillinger',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Many roles are trade-specific.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'hammer-hanborg', 'Hammer & Hanborg', 'Staffing / recruitment',
  'Specialist recruiter board', 'Norway / Nordics', 'High',
  'Norwegian + English', 'https://www.hammerhanborg.no/ledige-stillinger', 'https://www.hammerhanborg.no/ledige-stillinger',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Relevant to client-facing digital roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jefferson-wells-norway', 'Jefferson Wells Norway', 'Staffing / recruitment',
  'Specialist recruiter board', 'Norway', 'High',
  'Norwegian + English', 'https://www.jeffersonwells.no/nb/sok', 'https://www.jeffersonwells.no/nb/sok',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Part of the ManpowerGroup ecosystem.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'experis-norway', 'Experis Norway', 'Staffing / recruitment',
  'Specialist recruiter board', 'Norway', 'High',
  'Norwegian + English', 'https://www.experis.no/nb/sok', 'https://www.experis.no/nb/sok',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Technology-focused ManpowerGroup brand.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'sperton-norway', 'Sperton Norway', 'Staffing / recruitment',
  'Recruiter job board', 'Norway + global', 'High',
  'English + Norwegian', 'https://www.sperton.com/jobs/', 'https://www.sperton.com/jobs/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'International recruiter headquartered in Norway.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'nes-fircroft-norway', 'NES Fircroft Norway', 'Staffing / recruitment',
  'Specialist recruiter board', 'Norway', 'Medium',
  'English', 'https://www.nesfircroft.com/regions/recruitment-in-europe/norway-jobs/', 'https://www.nesfircroft.com/regions/recruitment-in-europe/norway-jobs/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Strongest in specialist technical sectors.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'meyerhaugen', 'MeyerHaugen', 'Staffing / recruitment',
  'Recruiter job board', 'Norway / Oslo', 'High',
  'Norwegian', 'https://meyerhaugen.no/ledige-stillinger/', 'https://meyerhaugen.no/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Oslo-oriented recruitment company.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'job-norway', 'Job Norway', 'Staffing / recruitment',
  'Sector recruiter board', 'Norway', 'Medium',
  'English', 'https://jobnorway.no/jobs/', 'https://jobnorway.no/jobs/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Targets international workers for Norwegian hospitality roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'toptemp', 'Toptemp', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://www.toptemp.no/ledige-stillinger', 'https://www.toptemp.no/ledige-stillinger',
  '2 Supplemental', 'Medium', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Broad staffing portfolio.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'capus', 'Capus', 'Staffing / recruitment',
  'Recruiter job board', 'Norway / Oslo', 'High',
  'Norwegian', 'https://capus.no/ledige-stillinger/', 'https://capus.no/ledige-stillinger/',
  '3 Niche', 'Medium', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Recruitment and executive-search oriented.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'people', 'People', 'Staffing / recruitment',
  'Recruiter job board', 'Norway', 'High',
  'Norwegian', 'https://people.no/ledige-stillinger', 'https://people.no/ledige-stillinger',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Current listings include Oslo retail and service roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'dreamwork', 'Dreamwork', 'Staffing / recruitment',
  'Recruiter job board', 'Norway / Oslo', 'High',
  'Norwegian', 'https://dreamwork.no/ledige-stillinger/', 'https://dreamwork.recman.io/',
  '1 Core', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Direct RecMan vacancy feed is searchable.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'logent-norway', 'Logent Norway', 'Staffing / recruitment',
  'Sector recruiter / employer board', 'Norway', 'High',
  'Norwegian + English', 'https://logent.no/en/work-at-logent/open-positions-no/', 'https://logent.no/en/work-at-logent/open-positions-no/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Relevant to stockroom and warehouse searches.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'legejobber', 'Legejobber', 'Healthcare',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://www.legejobber.no/', 'https://www.legejobber.no/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Professional healthcare board.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'dagens-medisin-jobb', 'Dagens Medisin Jobb', 'Healthcare',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://jobb.dagensmedisin.no/', 'https://jobb.dagensmedisin.no/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Medical industry publication’s job section.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'sykepleien-jobb', 'Sykepleien Jobb', 'Healthcare',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://jobb.sykepleien.no/', 'https://jobb.sykepleien.no/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Nurse-focused board.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'vacant-helse', 'Vacant Helse', 'Healthcare',
  'Healthcare staffing board', 'Norway', 'Medium',
  'Norwegian', 'https://vacant.no/ledige-stillinger/', 'https://vacant.no/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Healthcare staffing assignments.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'wrk-medic', 'WRK Medic', 'Healthcare',
  'Healthcare staffing board', 'Norway', 'Medium',
  'Norwegian', 'https://wrkmedic.no/ledige-stillinger/', 'https://wrkmedic.no/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Specialist healthcare recruiter.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'eccera-care', 'Eccera Care', 'Healthcare',
  'Healthcare staffing board', 'Norway', 'Medium',
  'Norwegian + Scandinavian', 'https://eccera.com/no/care/', 'https://eccera.com/no/care/',
  '3 Niche', 'Medium', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Current care-staffing brand associated with the former Centric Care area.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'dedicare-norway', 'Dedicare Norway', 'Healthcare',
  'Healthcare staffing board', 'Norway / Scandinavia', 'Medium',
  'Norwegian + Scandinavian', 'https://www.dedicare.no/jobb/', 'https://www.dedicare.no/jobb/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Cross-Nordic healthcare staffing.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'pacuramed', 'PacuraMed', 'Healthcare',
  'Healthcare staffing board', 'Norway', 'Medium',
  'Norwegian', 'https://pacuramed.no/ledige-stillinger/', 'https://pacuramed.no/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Large searchable healthcare assignment pool.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'medflow', 'Medflow', 'Healthcare',
  'Healthcare recruitment portal', 'Norway', 'Medium',
  'Norwegian', 'https://medflow.no/ledige-stillinger', 'https://medflow.no/ledige-stillinger',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Specialist medical recruitment.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'medicarrera-norway', 'MediCarrera Norway', 'Healthcare',
  'International healthcare recruiter', 'Norway / Europe', 'Low',
  'English', 'https://medicarrera.com/jobs-in-norway/', 'https://medicarrera.com/jobs-in-norway/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Often includes relocation and language requirements.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'helse-midt-norge-ledige-stillinger', 'Helse Midt-Norge – ledige stillinger', 'Healthcare',
  'Regional employer network', 'Central Norway', 'Low',
  'Norwegian', 'https://www.helse-midt.no/om-oss/om-oss-oversikt/ledige-stillinger/', 'https://www.helse-midt.no/om-oss/om-oss-oversikt/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Regional, not Oslo-focused.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'helse-nord-ledige-stillinger', 'Helse Nord – ledige stillinger', 'Healthcare',
  'Regional employer network', 'Northern Norway', 'Low',
  'Norwegian', 'https://www.helse-nord.no/om-oss/ledige-stillinger/', 'https://www.helse-nord.no/om-oss/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Regional, not Oslo-focused.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'kampanje-jobb', 'Kampanje Jobb', 'Media / communications',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://kampanje.com/jobb/', 'https://kampanje.com/jobb/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Strong specialist board for commercial communication roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'stilling-m24', 'Stilling M24', 'Media / communications',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://stilling.m24.no/', 'https://stilling.m24.no/',
  '3 Niche', 'High', 'Active; may be sparse',
  'agent', 'unreviewed', 1,
  'Operated by Medier24.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'mediejobb-journalisten', 'Mediejobb / Journalisten', 'Media / communications',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://www.mediejobb.no/', 'https://www.mediejobb.no/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Journalist-focused vacancies.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'arkitektur-ledige-stillinger', 'Arkitektur – ledige stillinger', 'Architecture / design',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://www.arkitektur.no/ledige-stillinger/', 'https://www.arkitektur.no/ledige-stillinger/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Current listings include Oslo architecture roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'dezeen-jobs-oslo', 'Dezeen Jobs – Oslo', 'Architecture / design',
  'Global design job board', 'Oslo filter', 'High',
  'English', 'https://www.dezeenjobs.com/location/oslo/', 'https://www.dezeenjobs.com/location/oslo/',
  '3 Niche', 'High', 'Active; sometimes zero listings',
  'unknown', 'unreviewed', 0,
  'Dedicated Oslo location page but volume can be sparse.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'scenekunst-no-stillingsannonser', 'Scenekunst.no Stillingsannonser', 'Culture / arts',
  'Sector vacancy board', 'Norway', 'High',
  'Norwegian', 'https://scenekunst.no/stillingsannonser', 'https://scenekunst.no/stillingsannonser',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Includes front-of-house and technical positions as well as artistic roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'advokatjobb', 'Advokatjobb', 'Legal / finance',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://advokatjobb.no/', 'https://advokatjobb.no/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Legal specialist board.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'rett24-stillinger', 'Rett24 Stillinger', 'Legal / finance',
  'Sector job board', 'Norway', 'High',
  'Norwegian', 'https://rett24.no/stillinger', 'https://rett24.no/stillinger',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Legal news publication’s vacancy section.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'efinancialcareers-norway', 'eFinancialCareers Norway', 'Legal / finance',
  'Global finance job board', 'Norway filter', 'High',
  'English', 'https://www.efinancialcareers.no/', 'https://www.efinancialcareers.no/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'International finance-focused source.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'acca-careers-norway', 'ACCA Careers Norway', 'Legal / finance',
  'Global accounting job board', 'Norway filter', 'Medium',
  'English', 'https://jobs.accaglobal.com/jobs/norway/', 'https://jobs.accaglobal.com/jobs/norway/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Specialist accounting source.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'impactpool-norway', 'Impactpool Norway', 'Impact / NGO',
  'International impact job board', 'Norway filter + global', 'High',
  'English', 'https://www.impactpool.org/search', 'https://www.impactpool.org/search',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Useful for organisations headquartered in Oslo and remote/international roles.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'developmentaid-norway', 'DevelopmentAid Norway', 'Impact / NGO',
  'International development job board', 'Norway filter', 'Medium',
  'English', 'https://www.developmentaid.org/jobs-in-norway', 'https://www.developmentaid.org/jobs-in-norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Specialist development-sector coverage.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'probably-good', 'Probably Good', 'Impact / NGO',
  'Impact job board', 'Global / remote', 'Medium',
  'English', 'https://probablygood.org/jobs', 'https://probablygood.org/jobs',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Use Norway/Europe/remote filters where available.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'the-impact-job', 'The Impact Job', 'Impact / NGO',
  'Impact job board', 'Europe / remote', 'Medium',
  'English', 'https://theimpactjob.com/', 'https://theimpactjob.com/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Supplementary European impact board.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'rigzone-norway', 'Rigzone Norway', 'Engineering / energy',
  'Global energy job board', 'Norway filter', 'Low',
  'English', 'https://www.rigzone.com/oil/jobs/search/?fl=Norway', 'https://www.rigzone.com/oil/jobs/search/?fl=Norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'More relevant outside Oslo, but some corporate and engineering roles appear.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'energy-jobline-norway', 'Energy Jobline Norway', 'Engineering / energy',
  'Global energy job board', 'Norway filter', 'Medium',
  'English', 'https://www.energyjobline.com/jobs/norway', 'https://www.energyjobline.com/jobs/norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Check original employer listing.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'omega-365-jobs', 'Omega 365 Jobs', 'Engineering / energy',
  'Consulting assignment portal', 'Norway + international', 'Medium',
  'English + Norwegian', 'https://omega365.com/jobs', 'https://omega365.com/jobs',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Recurring Norwegian consultant assignments.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'remote-rocketship-norway', 'Remote Rocketship Norway', 'Remote / global',
  'Remote-job aggregator', 'Remote from Norway', 'High',
  'English', 'https://www.remoterocketship.com/country/norway/', 'https://www.remoterocketship.com/country/norway/',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Dedicated Norway remote filter.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobgether-norway', 'Jobgether Norway', 'Remote / global',
  'Remote-job aggregator', 'Remote / Norway', 'High',
  'English', 'https://jobgether.com/remote-jobs/norway', 'https://jobgether.com/remote-jobs/norway',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Check geographic hiring eligibility carefully.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'eu-remote-jobs', 'EU Remote Jobs', 'Remote / global',
  'Remote job board', 'Europe incl. Norway', 'High',
  'English', 'https://euremotejobs.com/', 'https://euremotejobs.com/',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Better geographic fit than US-only remote boards.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'we-work-remotely', 'We Work Remotely', 'Remote / global',
  'Remote job board', 'Global', 'Medium',
  'English', 'https://weworkremotely.com/', 'https://weworkremotely.com/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Confirm that the employer can hire in Norway.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'nodesk', 'NoDesk', 'Remote / global',
  'Remote job board', 'Global', 'Medium',
  'English', 'https://nodesk.co/remote-jobs/', 'https://nodesk.co/remote-jobs/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Confirm Norway eligibility.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'arc-remote-jobs-norway', 'Arc Remote Jobs Norway', 'Remote / global',
  'Tech talent marketplace', 'Remote / Norway', 'High',
  'English', 'https://arc.dev/remote-jobs/norway', 'https://arc.dev/remote-jobs/norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Developer-heavy and often experience-sensitive.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'faruse-norway', 'Faruse Norway', 'Oslo / international',
  'English-language aggregator', 'Norway', 'Medium',
  'English', 'https://faruse.com/english-speaking/jobs/norway', 'https://faruse.com/english-speaking/jobs/norway',
  '3 Niche', 'Medium', 'Active; lower confidence',
  'agent', 'unreviewed', 1,
  'Use as a supplementary lead source and verify originals.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'right-people-group-norway', 'Right People Group Norway', 'Freelance / consulting',
  'Consultant assignment marketplace', 'Norway / Oslo', 'High',
  'English + Norwegian', 'https://rightpeoplegroup.com/no/find-consulting-projects/', 'https://rightpeoplegroup.com/no/find-consulting-projects/',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Project-based consulting rather than ordinary employment.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'ework-find-work', 'Ework – Find Work', 'Freelance / consulting',
  'Consultant assignment marketplace', 'Nordics incl. Norway', 'High',
  'English', 'https://www.eworkgroup.com/find-work', 'https://www.eworkgroup.com/find-work',
  '2 Supplemental', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Requires consultant profile and often substantial experience.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'emagine-assignments', 'emagine – assignments', 'Freelance / consulting',
  'Consultant assignment marketplace', 'Nordics / Europe incl. Norway', 'High',
  'English', 'https://emagine.org/consultants/available-assignments/', 'https://emagine.org/consultants/available-assignments/',
  '3 Niche', 'Medium', 'Verified active',
  'agent', 'unreviewed', 1,
  'Former ProData Consult ecosystem; senior-experience bias.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'freelancermap-norway', 'Freelancermap Norway', 'Freelance / consulting',
  'Freelance project board', 'Norway filter', 'High',
  'English', 'https://www.freelancermap.com/projects/norway', 'https://www.freelancermap.com/projects/norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Dedicated Norway project page; often senior contracts.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'jobbers-io-norway', 'Jobbers.io Norway', 'Freelance / consulting',
  'Freelance marketplace', 'Norway / Oslo filters', 'High',
  'English', 'https://www.jobbers.io/location/norway/', 'https://www.jobbers.io/location/norway/',
  '3 Niche', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Commission-free positioning; assess project quality individually.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'workana-norway', 'Workana Norway', 'Freelance / consulting',
  'Freelance marketplace', 'Norway client filter', 'Medium',
  'English + other', 'https://www.workana.com/en/jobs?country=NO', 'https://www.workana.com/en/jobs?country=NO',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Global marketplace; Norwegian project volume varies.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'twine-norway', 'Twine Norway', 'Freelance / consulting',
  'Creative freelance marketplace', 'Norway filter', 'Medium',
  'English', 'https://www.twine.net/jobs/in/norway', 'https://www.twine.net/jobs/in/norway',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Best for portfolio-based project work.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'upwork-norwegian-jobs', 'Upwork – Norwegian jobs', 'Freelance / consulting',
  'Freelance marketplace', 'Global / Norwegian-language work', 'High',
  'English + Norwegian', 'https://www.upwork.com/freelance-jobs/norwegian/', 'https://www.upwork.com/freelance-jobs/norwegian/',
  '2 Supplemental', 'High', 'Verified active',
  'unknown', 'unreviewed', 0,
  'Competitive global marketplace; fees and client quality vary.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog (
  id, platform, category, platform_type, scope, oslo_relevance, language,
  listings_url, source_url, priority, confidence, status,
  acquisition_tier, automation_policy, requires_premium, notes, verified_at
) VALUES (
  'payoutpartner-jobs', 'PayoutPartner Jobs', 'Freelance / consulting',
  'Gig / freelance partner portal', 'Norway', 'High',
  'Norwegian + English', 'https://www.payoutpartner.com/no/en/jobs/', 'https://www.payoutpartner.com/no/en/jobs/',
  '3 Niche', 'High', 'Verified active',
  'agent', 'unreviewed', 1,
  'Designed to support freelance work without establishing a company.', '2026-08-05'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'startupmatcher', 'Startupmatcher', 'Merged',
  'The Hub', 'Merged into The Hub in 2021; some official guidance still contains the old name.', 'https://thehub.io/jobs?countryCode=NO',
  '2026-08-05', 'High'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'graduateland', 'Graduateland', 'Merged / acquired',
  'JobTeaser', 'Acquired and incorporated into JobTeaser; use JobTeaser for current listings.', 'https://www.jobteaser.com/en/job-offers',
  '2026-08-05', 'High'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'centric-care', 'Centric Care', 'Rebranded / transitioned',
  'Eccera Care', 'Current healthcare staffing activity appears under Eccera Care.', 'https://eccera.com/no/care/',
  '2026-08-05', 'Medium'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'monster-no', 'Monster.no', 'Legacy / not verified active',
  'LinkedIn, FINN, Arbeidsplassen', 'Historic Norwegian portal; no current Norway-specific service verified.', '',
  '2026-08-05', 'Medium'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'jucan', 'Jucan', 'Legacy brand',
  'Webcruiter', 'Historic Webcruiter-associated job portal/brand; use Webcruiter’s current vacancy index.', 'https://candidate.webcruiter.com/nb-no/home/alladverts',
  '2026-08-05', 'Medium'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'kelly-services-norway', 'Kelly Services Norway', 'Legacy / uncertain',
  'Adecco, Manpower, Randstad', 'Appears in older Norwegian directories; current Norway vacancy portal not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'jobbdirekte-no', 'Jobbdirekte.no', 'Unverified / historical',
  'Arbeidsplassen, FINN', 'Found in older directory material but not independently verified as active.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'jobboffentlig-no', 'JobbOffentlig.no', 'Unverified / historical',
  'Kommunaljobb, Arbeidsplassen', 'Older public-sector portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'jobbportalen-no', 'Jobbportalen.no', 'Unverified / historical',
  'Arbeidsplassen, FINN', 'Older general portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'jobbtotal-no', 'Jobbtotal.no', 'Unverified / historical',
  'Jobbsafari, Indeed', 'Older aggregator reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'karriere-no', 'Karriere.no', 'Unverified / historical',
  'KarriereStart', 'Older portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'karriereplassen-no', 'KarrierePlassen.no', 'Unverified / historical',
  'Arbeidsplassen, FINN', 'Older portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'laererjobb-no', 'Lærerjobb.no', 'Unverified / historical',
  'Utdanningsnytt, Arbeidsplassen', 'Older education portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'horecajobb-no', 'Horecajobb.no', 'Unverified / historical',
  'Job Norway, FINN, Arbeidsplassen', 'Older hospitality portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'kommunikasjon-no-jobs', 'Kommunikasjon.no jobs', 'Unverified / historical',
  'Kampanje Jobb, M24', 'Older communications job section reference; current active vacancy index not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'medrec-no', 'Medrec.no', 'Unverified / historical',
  'Legejobber, Sykepleien Jobb', 'Older healthcare job portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'jobbforalle-no', 'Jobbforalle.no', 'Unverified / historical',
  'Arbeidsplassen', 'Older inclusion-oriented portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'inkludi-no', 'Inkludi.no', 'Unverified / historical',
  'Arbeidsplassen', 'Older inclusion-oriented portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'instacruit', 'Instacruit', 'Legacy / uncertain',
  'LinkedIn, MeetFrank', 'App-based recruitment service seen in older sources; current Norway job-board status not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'mojob', 'Mojob', 'Legacy / uncertain',
  'LinkedIn, MeetFrank', 'Mobile recruitment platform seen in older sources; current Norway activity not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'jobbreg', 'Jobbreg', 'Unverified / historical',
  'Webcruiter, Jobbnorge', 'Older recruitment portal reference; current active service not verified.', '',
  '2026-08-05', 'Low'
);
INSERT OR REPLACE INTO source_catalog_legacy (
  id, platform, current_status, use_instead, reason, replacement_url,
  checked_at, confidence
) VALUES (
  'legejobb-no-singular', 'Legejobb.no (singular)', 'Legacy / ambiguous',
  'Legejobber.no', 'Older directory used a similar singular name; current verified service is Legejobber.no.', 'https://www.legejobber.no/',
  '2026-08-05', 'Low'
);
