-- Generated by scripts/ts/schema.ts from the domain models.
-- Column names are derived; types, keys, and indexes are declared in that
-- script and checked against the models. Re-run with --emit after a model
-- changes. Nothing else may edit this file.

CREATE TABLE IF NOT EXISTS answers (
  profileId TEXT NOT NULL,
  question TEXT NOT NULL,
  label TEXT NOT NULL,
  shape TEXT NOT NULL,
  value TEXT NOT NULL,
  origin TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (profileId, question)
);

CREATE TABLE IF NOT EXISTS delivery_platforms (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  hostPattern TEXT NOT NULL,
  tier TEXT NOT NULL,
  mappings TEXT NOT NULL DEFAULT '[]',
  automationProhibited INTEGER NOT NULL DEFAULT 0 CHECK (automationProhibited IN (0,1)),
  learnedAt TEXT,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_delivery_platforms_hostPattern ON delivery_platforms (hostPattern);

CREATE TABLE IF NOT EXISTS submissions (
  id TEXT NOT NULL,
  profileId TEXT NOT NULL,
  platformId TEXT NOT NULL,
  applicationUrl TEXT NOT NULL,
  viaTier TEXT NOT NULL,
  outcome TEXT NOT NULL,
  humanIntervened INTEGER NOT NULL DEFAULT 0 CHECK (humanIntervened IN (0,1)),
  unanswered TEXT NOT NULL DEFAULT '[]',
  detail TEXT NOT NULL DEFAULT '',
  createdAt TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_submissions_profileId ON submissions (profileId);

CREATE INDEX IF NOT EXISTS idx_submissions_platformId ON submissions (platformId);

CREATE TABLE IF NOT EXISTS freshness (
  profileId TEXT NOT NULL,
  seenThrough INTEGER NOT NULL DEFAULT 0,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (profileId)
);

CREATE TABLE IF NOT EXISTS judgements (
  profileId TEXT NOT NULL,
  jobId TEXT NOT NULL,
  verdict TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  createdAt TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_judgements_profileId_jobId ON judgements (profileId, jobId);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT NOT NULL,
  principalId TEXT NOT NULL,
  profileId TEXT NOT NULL,
  tokenHash TEXT NOT NULL,
  expiresAt INTEGER NOT NULL,
  createdAt TEXT NOT NULL,
  revokedAt TEXT,
  PRIMARY KEY (id),
  UNIQUE (tokenHash)
);

CREATE INDEX IF NOT EXISTS idx_sessions_principalId ON sessions (principalId);

CREATE TABLE IF NOT EXISTS subscriptions (
  profileId TEXT NOT NULL,
  tier TEXT NOT NULL,
  providerRef TEXT NOT NULL DEFAULT '',
  provider TEXT NOT NULL DEFAULT 'none',
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (profileId)
);

CREATE TABLE IF NOT EXISTS profiles (
  profileId TEXT NOT NULL,
  cv TEXT NOT NULL,
  erasure TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (profileId)
);

CREATE TABLE IF NOT EXISTS principals (
  principalId TEXT NOT NULL,
  profileId TEXT NOT NULL,
  apiKeyHash TEXT NOT NULL,
  revokedAt TEXT,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (principalId),
  UNIQUE (apiKeyHash)
);

CREATE INDEX IF NOT EXISTS idx_principals_profileId ON principals (profileId);

CREATE TABLE IF NOT EXISTS source_catalog (
  id TEXT NOT NULL,
  platform TEXT NOT NULL,
  category TEXT NOT NULL,
  listingsUrl TEXT NOT NULL,
  tierTag TEXT NOT NULL CHECK (tierTag IN ('Feed', 'Scripted', 'Agent', 'Unknown')),
  policyTag TEXT NOT NULL DEFAULT 'Unreviewed' CHECK (policyTag IN ('Allowed', 'AssistedOnly', 'Prohibited', 'Unreviewed')),
  requiresPremium INTEGER NOT NULL DEFAULT 0 CHECK (requiresPremium IN (0,1)),
  priority TEXT NOT NULL,
  confidence TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  verifiedAt TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_source_catalog_tierTag ON source_catalog (tierTag);

CREATE TABLE IF NOT EXISTS canonical_jobs (
  id TEXT NOT NULL,
  canonicalKey TEXT NOT NULL,
  title TEXT NOT NULL,
  employerName TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  applicationUrl TEXT NOT NULL,
  publishedAt TEXT NOT NULL,
  deadline TEXT,
  statusTag TEXT NOT NULL CHECK (statusTag IN ('Active', 'Closed')),
  statusClosedAt TEXT,
  sequence INTEGER NOT NULL,
  changedAt TEXT NOT NULL,
  sources TEXT NOT NULL DEFAULT '[]',
  titleNormalized TEXT NOT NULL,
  employerNameNormalized TEXT NOT NULL,
  locationNormalized TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (canonicalKey)
);

CREATE INDEX IF NOT EXISTS idx_canonical_jobs_sequence ON canonical_jobs (sequence);

CREATE INDEX IF NOT EXISTS idx_canonical_jobs_statusTag_sequence ON canonical_jobs (statusTag, sequence);

CREATE TABLE IF NOT EXISTS occurrences (
  id TEXT NOT NULL,
  canonicalJobId TEXT NOT NULL,
  sourceId TEXT NOT NULL,
  externalId TEXT NOT NULL,
  contentFingerprint TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  firstSeenAt TEXT NOT NULL,
  lastSeenAt TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (sourceId, externalId)
);

CREATE INDEX IF NOT EXISTS idx_occurrences_canonicalJobId ON occurrences (canonicalJobId);

CREATE INDEX IF NOT EXISTS idx_occurrences_sourceId_active ON occurrences (sourceId, active);

CREATE TABLE IF NOT EXISTS saved_jobs (
  id TEXT NOT NULL,
  profileId TEXT NOT NULL,
  canonicalJobId TEXT NOT NULL,
  jobSnapshot TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  createdAt TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (profileId, canonicalJobId)
);

CREATE INDEX IF NOT EXISTS idx_saved_jobs_profileId ON saved_jobs (profileId);

CREATE TABLE IF NOT EXISTS applications (
  id TEXT NOT NULL,
  profileId TEXT NOT NULL,
  savedJobId TEXT NOT NULL,
  canonicalJobId TEXT NOT NULL,
  jobSnapshot TEXT NOT NULL,
  method TEXT NOT NULL CHECK (method IN ('assisted', 'automated')),
  status TEXT NOT NULL CHECK (status IN ('ready', 'submitted', 'rejected', 'interview', 'offer', 'withdrawn')),
  applicationUrl TEXT NOT NULL,
  cv TEXT NOT NULL,
  letter TEXT NOT NULL,
  generator TEXT NOT NULL,
  downgradeReason TEXT,
  notes TEXT NOT NULL DEFAULT '',
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_applications_profileId ON applications (profileId);

CREATE INDEX IF NOT EXISTS idx_applications_savedJobId ON applications (savedJobId);

CREATE TABLE IF NOT EXISTS platform_policies (
  platformId TEXT NOT NULL,
  policy TEXT NOT NULL CHECK (policy IN ('Allowed', 'AssistedOnly', 'Prohibited', 'Unreviewed')),
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (platformId)
);

CREATE TABLE IF NOT EXISTS source_state (
  platformId TEXT NOT NULL,
  cursor TEXT NOT NULL,
  seenExternalIds TEXT NOT NULL DEFAULT '[]',
  resolvedSourceId TEXT,
  leaseOwner TEXT,
  leaseExpiresAt INTEGER,
  updatedAt TEXT NOT NULL,
  PRIMARY KEY (platformId)
);

CREATE TABLE IF NOT EXISTS ingestion_runs (
  platformId TEXT NOT NULL,
  startedAt TEXT NOT NULL,
  pages INTEGER NOT NULL,
  observations INTEGER NOT NULL,
  canonicalChanges INTEGER NOT NULL,
  cursorBefore TEXT NOT NULL,
  cursorAfter TEXT NOT NULL,
  highestSequence INTEGER NOT NULL,
  stoppedReason TEXT NOT NULL,
  durationMs INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ingestion_runs_platformId_startedAt ON ingestion_runs (platformId, startedAt);

CREATE TABLE IF NOT EXISTS ingestion_failures (
  platformId TEXT NOT NULL,
  occurredAt TEXT NOT NULL,
  failureTag TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  cursor TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ingestion_failures_platformId_occurredAt ON ingestion_failures (platformId, occurredAt);
