-- Generated by scripts/ts/schema.ts from the domain models.
-- Column names are derived; types are declared in that script and reviewed.
-- Re-run with --emit after a model changes. Nothing else may edit this file.

CREATE TABLE IF NOT EXISTS answers (
  profileId TEXT NOT NULL,
  question TEXT NOT NULL,
  label TEXT NOT NULL,
  shape TEXT NOT NULL,
  value TEXT NOT NULL,
  origin TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS delivery_platforms (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  hostPattern TEXT NOT NULL,
  tier TEXT NOT NULL,
  mappings TEXT NOT NULL DEFAULT '[]',
  automationProhibited INTEGER NOT NULL DEFAULT 0 CHECK (automationProhibited IN (0,1)),
  learnedAt TEXT,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS submissions (
  id TEXT PRIMARY KEY,
  profileId TEXT NOT NULL,
  platformId TEXT NOT NULL,
  applicationUrl TEXT NOT NULL,
  viaTier TEXT NOT NULL,
  outcome TEXT NOT NULL,
  humanIntervened INTEGER NOT NULL DEFAULT 0 CHECK (humanIntervened IN (0,1)),
  unanswered TEXT NOT NULL DEFAULT '[]',
  detail TEXT NOT NULL DEFAULT '',
  createdAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS freshness (
  profileId TEXT NOT NULL,
  seenThrough INTEGER NOT NULL DEFAULT 0,
  updatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS judgements (
  profileId TEXT NOT NULL,
  jobId TEXT NOT NULL,
  verdict TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  createdAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  principalId TEXT NOT NULL,
  profileId TEXT NOT NULL,
  tokenHash TEXT NOT NULL,
  expiresAt INTEGER NOT NULL,
  createdAt TEXT NOT NULL,
  revokedAt TEXT
);

CREATE TABLE IF NOT EXISTS subscriptions (
  profileId TEXT NOT NULL,
  tier TEXT NOT NULL,
  providerRef TEXT NOT NULL DEFAULT '',
  provider TEXT NOT NULL DEFAULT 'none',
  updatedAt TEXT NOT NULL
);
