#!/usr/bin/env python3
"""Generates the source-catalog seed migration from the researched platform index.

The spreadsheet under research/input/ is the source of truth for which
platforms exist and how they rank. The seed migration is a derivation of it, so
it is generated rather than hand-maintained: editing the SQL by hand would let
the two disagree, and the sheet would stop being authoritative.

Re-run after editing the sheet:

    python3 scripts/import_source_index.py

The output is deterministic for a given sheet, so a no-op edit produces no diff.
Reads the workbook with the standard library because a build-time dependency on
an Excel reader would not survive the pinned Nix environment.
"""

from __future__ import annotations

import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree

ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = ROOT / "research/input/norway_oslo_job_platform_index.xlsx"
OUTPUT = ROOT / "migrations/0007_source_catalog_seed.sql"
NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"

# Platforms whose listings are reachable through an official machine-readable
# endpoint, or through an adapter we can write without driving a browser.
# Everything absent from this table stays 'unknown' until someone establishes
# how it may be read; ingestion never guesses.
ACQUISITION_TIERS = {
    "Arbeidsplassen (NAV)": ("feed", "assisted_only"),
    "FINN Jobb": ("scripted", "prohibited"),
    "Jobbnorge": ("scripted", "assisted_only"),
    "Webcruiter": ("scripted", "assisted_only"),
    "LinkedIn Jobs": ("agent", "prohibited"),
    "Indeed Norway": ("agent", "prohibited"),
    "Glassdoor Norway": ("agent", "prohibited"),
    "EURES": ("feed", "assisted_only"),
    "Oslo kommune – ledige stillinger": ("scripted", "assisted_only"),
    "Politiet – ledige stillinger": ("scripted", "assisted_only"),
    "Forsvaret – ledige stillinger": ("scripted", "assisted_only"),
    "The Hub": ("scripted", "assisted_only"),
    "Kodejobb": ("scripted", "assisted_only"),
    "Tekjobb": ("scripted", "assisted_only"),
}


def cell_values(sheet_xml: bytes, shared: list[str]) -> list[list[str]]:
    rows: list[list[str]] = []
    for row in ElementTree.fromstring(sheet_xml).iter(f"{NS}row"):
        values: list[str] = []
        for cell in row.iter(f"{NS}c"):
            value = cell.find(f"{NS}v")
            if value is None or value.text is None:
                values.append("")
            elif cell.get("t") == "s":
                values.append(shared[int(value.text)])
            else:
                values.append(value.text)
        if any(value.strip() for value in values):
            rows.append(values)
    return rows


def slug(value: str) -> str:
    normalized = value.strip().lower()
    normalized = normalized.replace("æ", "ae").replace("ø", "o").replace("å", "a")
    normalized = re.sub(r"[^a-z0-9]+", "-", normalized).strip("-")
    return normalized or "unnamed"


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def column(row: list[str], index: int) -> str:
    return row[index].strip() if index < len(row) else ""


def main() -> None:
    archive = zipfile.ZipFile(WORKBOOK)
    shared = [
        "".join(node.text or "" for node in item.iter(f"{NS}t"))
        for item in ElementTree.fromstring(
            archive.read("xl/sharedStrings.xml")
        ).iter(f"{NS}si")
    ]

    active = cell_values(archive.read("xl/worksheets/sheet2.xml"), shared)[1:]
    legacy = cell_values(archive.read("xl/worksheets/sheet3.xml"), shared)[1:]

    lines = [
        "-- Generated by scripts/import_source_index.py from",
        "-- research/input/norway_oslo_job_platform_index.xlsx. Do not edit by hand:",
        "-- re-run the importer so the sheet stays the single source of truth.",
        "",
    ]

    seen: set[str] = set()
    for row in active:
        platform = column(row, 0)
        if not platform:
            continue
        identifier = slug(platform)
        if identifier in seen:
            continue
        seen.add(identifier)

        tier, policy = ACQUISITION_TIERS.get(platform, ("unknown", "unreviewed"))
        lines.append(
            "INSERT OR REPLACE INTO source_catalog (\n"
            "  id, platform, category, platform_type, scope, oslo_relevance, language,\n"
            "  listings_url, source_url, priority, confidence, status,\n"
            "  acquisition_tier, automation_policy, requires_premium, notes, verified_at\n"
            ") VALUES (\n"
            f"  {quote(identifier)}, {quote(platform)}, {quote(column(row, 1))},\n"
            f"  {quote(column(row, 2))}, {quote(column(row, 3))}, {quote(column(row, 4))},\n"
            f"  {quote(column(row, 5))}, {quote(column(row, 12))}, {quote(column(row, 13))},\n"
            f"  {quote(column(row, 8))}, {quote(column(row, 15))}, {quote(column(row, 9) or 'active')},\n"
            f"  {quote(tier)}, {quote(policy)}, {1 if tier == 'agent' else 0},\n"
            f"  {quote(column(row, 11))}, {quote(column(row, 14))}\n"
            ");"
        )

    seen_legacy: set[str] = set()
    for row in legacy:
        platform = column(row, 0)
        if not platform:
            continue
        identifier = slug(platform)
        if identifier in seen_legacy:
            continue
        seen_legacy.add(identifier)
        lines.append(
            "INSERT OR REPLACE INTO source_catalog_legacy (\n"
            "  id, platform, current_status, use_instead, reason, replacement_url,\n"
            "  checked_at, confidence\n"
            ") VALUES (\n"
            f"  {quote(identifier)}, {quote(platform)}, {quote(column(row, 1))},\n"
            f"  {quote(column(row, 2))}, {quote(column(row, 3))}, {quote(column(row, 4))},\n"
            f"  {quote(column(row, 5))}, {quote(column(row, 6))}\n"
            ");"
        )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    agents = sum(
        1 for row in active if ACQUISITION_TIERS.get(column(row, 0), ("unknown",))[0] == "agent"
    )
    print(
        f"wrote {OUTPUT.relative_to(ROOT)}: {len(seen)} platforms "
        f"({agents} agent-tier), {len(seen_legacy)} legacy entries"
    )


if __name__ == "__main__":
    main()
