/**
 * The intended shape of the tables `observe.ts`/`queries.ts`/`freshness.ts`
 * read and write, in the exact column order `rows.ts`/`sql.ts` assume.
 *
 * NOT part of `db/schema.sql`, and not executed anywhere — this is
 * documentation, not a second schema source of truth. That snapshot is
 * generated by `scripts/ts/schema.ts` from `Model.Class` domain models
 * (`packages/domain/src/{Answer,Delivery,Freshness,Access,Subscription}.ts`),
 * and `Job.ts`'s `CanonicalJob`/`RawListing`/`NormalizedListing` are plain
 * `Schema.Struct`s, not `Model.Class`es — so the generator never sees them
 * and `canonical_jobs`/`occurrences` do not exist in the frozen snapshot.
 * This is a contract gap reported alongside this slot's other output (see
 * the corpus slot's final report): `db/schema.sql` is owned by nobody in
 * Phase 1, so this slot cannot fix it without editing a file outside
 * `apps/worker/src/corpus/**`.
 *
 * `testSupport.ts`'s fake `Database` does not execute this DDL against a
 * real engine, because no SQL engine is usable from this workspace without
 * a `package.json` edit this slot does not own: `bun:sqlite` has no type
 * declarations without the (uninstalled) `bun-types` package, and
 * `node:sqlite` is unimplemented on the pinned Bun (1.3.13, verified by
 * running it). The fake is a hand-rolled in-memory dispatcher instead (see
 * that file). Once `db/schema.sql` gains real tables for this shape, this
 * comment — and ideally this whole file — should be deleted in favour of it,
 * not kept in sync by hand.
 *
 * `freshness` is deliberately absent here: that table already exists in
 * `db/schema.sql` (generated from `Freshness.ts`), so there is nothing to
 * document — see `sql.ts`'s freshness statements instead.
 */
export const CORPUS_TABLE_SHAPE_DDL = `
CREATE TABLE IF NOT EXISTS canonical_jobs (
  id TEXT PRIMARY KEY,
  canonicalKey TEXT NOT NULL,
  title TEXT NOT NULL,
  employerName TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  applicationUrl TEXT NOT NULL,
  publishedAt TEXT NOT NULL,
  deadline TEXT,
  statusTag TEXT NOT NULL CHECK (statusTag IN ('Active', 'Closed')),
  statusClosedAt TEXT,
  sequence INTEGER NOT NULL,
  changedAt TEXT NOT NULL,
  sources TEXT NOT NULL DEFAULT '[]'
);

CREATE INDEX IF NOT EXISTS idx_canonical_jobs_sequence ON canonical_jobs(sequence);
CREATE INDEX IF NOT EXISTS idx_canonical_jobs_canonical_key ON canonical_jobs(canonicalKey);

CREATE TABLE IF NOT EXISTS occurrences (
  id TEXT PRIMARY KEY,
  canonicalJobId TEXT NOT NULL,
  sourceId TEXT NOT NULL,
  externalId TEXT NOT NULL,
  contentFingerprint TEXT NOT NULL,
  firstSeenAt TEXT NOT NULL,
  lastSeenAt TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_occurrences_canonical_job ON occurrences(canonicalJobId);
`;
